Fixed issue #1
UnicodeDecodeError: 'charmap' codec can't decode #1

Because the file encoding is different, I inserted 'encoding="utf8"' to the log function on line 63 of the file /shazam_music_downloader.py.